### ISSUE TITLE
Implement comment on table changing for table diff

### ISSUE THREAD

**Issue by dk1844** [AbsaOSS/ultet#3] opened 2023-10-12 08:49 UTC
Table diff is missing comment changing.

SQLs can look similar to this
```sql
COMMENT ON TABLE temp."Foo"
  IS 'Foo table!';
```

or 
```sql
COMMENT ON TABLE temp."Foo"
  IS NULL;
```

**Comment by benedeki** [comment] 2024-02-19 23:10
Duplicate of #34

**Closed by benedeki** 2024-02-19 23:10 UTC
Labels: enhancement
